server:
  port: 8080

spring:
  application:
    name: store-management
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL@gmail.com
    password: YOUR_APP_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  datasource:
    url: jdbc:h2:file:./data/finsen_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 5000
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

app:
  jwt:
    secret: 9A45B951804E1F0314486580971D5745F5428F322303036495147814E6966627
    expiration: 86400000 # 24 hours
