server:
  port: 8080

spring:
  application:
    name: store-management
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL@gmail.com
    password: YOUR_APP_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  datasource:
    url: ${LIVE_DB_URL:jdbc:postgresql://ep-silent-flower-a5s0z84j.us-east-2.aws.neon.tech/neondb?sslmode=require}
    driver-class-name: org.postgresql.Driver
    username: ${LIVE_DB_USER:neondb_owner}
    password: ${LIVE_DB_PASS:npg_x7LQRX9gW8vJ}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

app:
  jwt:
    secret: 9A45B951804E1F0314486580971D5745F5428F322303036495147814E6966627
    expiration: 86400000 # 24 hours
